<a href="https://colab.research.google.com/github/monicaqroz/livro_py/blob/main/Numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [7]:
a.itemsize

8

In [9]:
a.size

15

In [10]:
type(a)

numpy.ndarray

In [12]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [14]:
c = np.array([(1.5,2,3),(4,5,6)])
c

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [15]:
d = np.array([[1,2],[3,4]], dtype = complex)
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)